### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by firedev** [trailblazer/cells-slim#1]
Trying to use cells, and it seems to me `cells-slim` doesn't work. Any advice here?

```
Template missing: view: `show.erb` prefixes: ["staff"] view_paths:["app/cells"]
```

**Comment by sdesbure** [comment]
Hello, if you have several cells-XXX, the last(?) one will be the winner. You have to choose one (had the same issue)

**Comment by apotonick** [comment]
cells-slim-0.0.2 works great!
