### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by mrbongiolo** [trailblazer/cells-slim#21]
@apotonick would it be possible to release a `0.0.6` of this gem? Right now I have to use the master version on GH to make it work with rails 5.1.

**Comment by apotonick** [comment]
@georgemillo I added you as a gem owner! :wink: Thx

**Comment by george-carlin** [comment]
@apotonick  are you sure?

<img width="636" alt="screen shot 2018-04-11 at 17 35 56" src="https://user-images.githubusercontent.com/2656485/38630431-d475fe5e-3dae-11e8-9020-964e462cd4be.png">

:'(

**Comment by apotonick** [comment]
Fixed!

**Comment by george-carlin** [comment]
Annnnnd we are [live](https://rubygems.org/gems/cells-slim/versions/0.0.6)!
