### ISSUE TITLE
Don't work capture method with slim 5.2.0 and rails 7.1.2

### ISSUE THREAD

**Issue by AlfonsoUceda** [trailblazer/cells-slim#27]
Hi folks,

I'm trying to upgrade rails to version 7.1.2 (current 7.0.8) and slim to 5.2.0 (current 4.1.0) when I run the app and trying to get the root page I see the following error:
> undefined method `capture' for ["<div class=\"summary-item\">"]:Cell::ViewModel::OutputBuffer

This error happens because I have this overwrite in an initializer:
```ruby
module Cell
  module Slim
    def template_options_for(_options)
      {
        template_class: ::Slim::Template,
        suffix: "slim",
        disable_escape: false,
        escape_code: false,
        use_html_safe: true,
        buffer: "@output_buffer",
        generator: Temple::Generators::RailsOutputBuffer
      }
    end
  end
end
```
but if I comment the generator option I get:
```
undefined method `capture' for "<div class=\"summary-item\">":String
```

I'm not aware why we use the generator option but I will try to understand. The key point is that I don't understand why this not work.

The cell trying to render has the following code:
```ruby
class Dashboard::Cell::SummaryItem < Trailblazer::Cell
  def card(&block)
    element = :div
    options = { class: [:card, (:"#{status}-item" if status)].compact }

    if path.present?
      element = :a
      options[:href] = path
    end

    content_tag element, options, &block
  end
end
```
and the `card` method is used in the slim file like
```slim
.summary-item
  = card do
    section.counter
      .image-wrapper
        = vite_image_tag icon
      span = count

    span.label = label
    span.description = description

  .btn-container.stretch
    = button
```

When I comment the code to avoid this rendering I get more errors similar to that one:
> undefined method `capture' for "SOMETHING":String

Using slim 4.1.0 I suffer the same problem with similar instance:
> undefined method `capture' for "<div class=\"summary-item\">":ActiveSupport::SafeBuffer
and commeting the generate is the same error related to `String`

It seems that error happens because the @output_buffer for the instance of class `Dashboard::Cell::SummaryItem` is that string or safebuffer

**Comment by AlfonsoUceda** [comment]
The only fix I found to render things correctly, but not battle tested, is here: https://github.com/trailblazer/cells/blob/v4.1.7/lib/cell/view_model.rb#L154

change it to use `ActionView::OutputBuffer.new`. It seems this code was written 7 years ago but the code in master is different.

**Comment by apotonick** [comment]
Hi @AlfonsoUceda, thanks for digging here. I regret having to tell you I won't dive again into Rails view layer, especially with Github's `ViewComponent` that has dedicated people to develop the "new Cells" on a daily basis. :broken_heart: I am going to dedicate some time to the new Cells 5, which, so far only supports `ERBse` as that's the template engine we use for our products.

I'm happy to help here but I will never again attempt to sort out Rails' crazy world of output buffers and semi-global variables. :coffee:

**Comment by AlfonsoUceda** [comment]
@apotonick thank you for your time man. I understand and it makes totally sense to not waste time in the swamp xD

I see that version 4.2.0 should be released https://github.com/trailblazer/cells/commit/86a8f428beeef3089b26265c93b186e76ada03aa but this didn't happen, is it possible to create a release for this version? Maybe I should test cells with this commit and the removal of the OutputBuffer.

Will cells v5 work only with ERB? Or could be used also with Slim even if you don't support it?

**Comment by apotonick** [comment]
There was a problem with 4.2.0, which is why we didn't release it. This was another's work, I'm afraid I can't remember what was the issue here. As I said, with `ViewComponent` and paid developers I don't see why I should go back and hang out in the swamp :laughing: ...

We can surely try and make Cells 5 work with Slim. The only problem will be, you guessed it, `OutputBuffer` but maybe the internals in Rails have changed recently so it won't be too hard?

**Comment by AlfonsoUceda** [comment]
@apotonick 👍 I've tested that version and using the monkey patch I'm already using it works correctly, at least it is rendering correctly.
```ruby
module Cells
  class ViewModel
    # Overriding output_buffer fixes rendering
    def output_buffer
      ActionView::OutputBuffer.new
    end
  end
end
```
For now we are going to use cells because we have a lot them and migrate it to ViewComponent with knowing it will correctly it will be time taking, in addition supports `build` method which it is important for us :)

I'm going to follow Cells v5 release closely but if you need some help just tell me ;)

**Comment by apotonick** [comment]
Would you mind showing me how you use `Cell.build`? At the present moment we can still design Cells 5's API, so better to discuss now than too late :stuck_out_tongue: 

Also, you're using `Trailblazer::Cell`, right? Don't you find the file structure a bit awkward (still)? In Cells 5 it will be much simpler to have any kind of structure, so I currently do

```
cells/
  docs/
    index.rb
    index.erb
    ...
```

where the Ruby file and the view live in the same directory. Looking forward to opinions here.

**Comment by AlfonsoUceda** [comment]
We don't call build ourself in production code directly (just in tests), I think it is because cells `alias build new` so that's how it is called using the `cell` helper, then we implement it in our cells like this:
```ruby
class MyCell < Trailblazer::Cell
  dependency :my_dependency, MyDepedency
  
  def self.build
    instance = new
    MyDepedency.configure(instance
    instance
  end

  #...
end
```
`dependency` macro is from [dependency eventide project](https://github.com/eventide-project/dependency) so this allow us in tests to test the cell in isolation controlling the dependencies

**Comment by AlfonsoUceda** [comment]
About the file structure, I've found a bit annoying to navigate between `cell` and `view` folders, it would be nice to allow both like `ViewComponent` does, also for migration would be nice.

**Comment by samstickland** [comment]
@apotonick The purpose of using `build` is control whether dependencies are live or not. Outside of cells we use this pattern like this:

```ruby
class SomeObject
  dependency :fetch_some_data, FetchSomeData

  def self.call(...)
    build.(...)
  end

  def build
    instance = new
    FetchSomeData.configure(instance)
    instance
  end

  def call
    do_something
  end
end
```

When the object is "built" then the dependency FetchSomeData is live.. So this uses a live version of `FetchSomeData`

```ruby
SomeObject.()
```

But if the object is initialized without "building" then FetchSomeData is set to a substitute version, which you can think of as a "test" version (but Scott Bellware would have me shot for calling a substitute version a "test" version). So when ran like this, we get a non-live FetchSomeData

```ruby
instance = SomeObject.new
instance.()
```

And that allows us to control what FetchSomeData does in tests, without any need for stubbing.. For example:

```ruby
instance = SomeObject.new
instance.fetch_some_data.set_data(some_data)

instance.()

assert.fetch_some_data_data.called_with?(some_arg: :some_value)
```

**Comment by samstickland** [comment]
More information here: http://docs.eventide-project.org/user-guide/useful-objects.html
